### ISSUE TITLE
Georeferencing Error: Records found outside named county > .5 mile

### ISSUE THREAD

**Issue by dbloom** [mvz-vertnet/mvz-herp#26]
Hello MVZ,

The Kentucky Department of Fish & Wildlife Resources, Fish and Wildlife Information System (KFWIS) have identified 14 records in the VertNet data portal that should plot within the bounds of the named county in the state of Kentucky, but actually plot outside the named county by half a mile or more.

If you'd like to discuss these issues with the folks at KFWIS, contact me and I will connect you with them.

Records below are Tab-Separated so you should be able to cut/paste into a spreadsheet so you can read them more easily.

institutioncode	collectioncode	catalognumber	county	decimallatitude	decimallongitude	geodeticdatum	coordinateuncertaintyinmeters
MVZ	Amphibian and reptile specimens	29785	Rockcastle County	37.1902	-84.1183	North American Datum 1927	347
MVZ	Amphibian and reptile specimens	29786	Rockcastle County	37.1902	-84.1183	North American Datum 1927	347
MVZ	Amphibian and reptile specimens	178579	Rockcastle County	37.4155	-82.5465	North American Datum 1927	830
MVZ	Amphibian and reptile specimens	178582	Whitley County	36.8358	-84.359	North American Datum 1927	2439
MVZ	Amphibian and reptile specimens	178578	Rockcastle County	37.4155	-82.5465	North American Datum 1927	830
MVZ	Amphibian and reptile specimens	178580	Whitley County	36.8358	-84.359	North American Datum 1927	2439
MVZ	Amphibian and reptile specimens	178581	Whitley County	36.8358	-84.359	North American Datum 1927	2439
MVZ	Amphibian and reptile specimens	178583	Whitley County	36.8358	-84.359	North American Datum 1927	2439
MVZ	Amphibian and reptile specimens	29787	Rockcastle County	37.1902	-84.1183	North American Datum 1927	347
MVZ	Amphibian and reptile specimens	183927	Harlan County	36.7493	-83.7172	North American Datum 1927	24165
MVZ	Amphibian and reptile specimens	183926	Harlan County	36.7493	-83.7172	North American Datum 1927	24165
MVZ	Amphibian and reptile specimens	32468	Rockcastle County	37.1902	-84.1183	North American Datum 1927	1635
MVZ	Amphibian and reptile specimens	32466	Rockcastle County	37.1902	-84.1183	North American Datum 1927	1635
MVZ	Amphibian and reptile specimens	32467	Rockcastle County	37.1902	-84.1183	North American Datum 1927	1635

 (There may not be data contained within each Darwin Core field for each of these records.)

**Comment by mkoo** [comment]
Adding to task queue...

**Comment by mkoo** [comment]
Closed and fixed by KLyberger, 7 May 2015
